<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="shortcut icon" href="/images/logo.png" type="image/x-icon" />
  <link rel="apple-touch-icon" href="/images/logo.png" />
  <?= $this->headTitle(); ?>
  <?= $this->headMeta(); ?>
  <?= $this->headScript(); ?>
  <?//= $this->headLink()->prependStylesheet('/css/style.css'); ?>
  
  <!-- Scripts -->
  <?//= $this->headScript()->prependFile('/js/jquery.js') ?>
  
</head>
<body>

<?=$this->render("layout/common/header");?>
<?=$this->layout()->content; ?>
<?=$this->render("layout/common/footer");?>

</body>

</html>
